### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "alvaro@gmail.com",
  "password": "hola"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/

### Find users with a given email
GET http://localhost:3000/auth?emai=nico@gmail.com

### Update user 
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
"email": "ojitoehgmail.com"
}

### Delete user by ID
DELETE http://localhost:3000/auth/4

### User signIn
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "daniela@gmail.com",
  "password": "hola"
}

### User signOut
POST http://localhost:3000/auth/signout

### Verify who owns the session
GET http://localhost:3000/auth/whoami

### List all users
# GET http://localhost:3000/auth/list
