### REPORTS

### Create Report of a sold car
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Fiat",
  "model": "Uno",
  "year": 1998,
  "mileage": 400000,
  "lng": 0,
  "lat": 0,
  "price": 1500,
  "approved": 0
}

### Approve an existing report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": 1
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Fiat&model=Uno&lng=0&lat=0&mileage=300000&year=1996

